spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require[cite: 13]
    username: postgres.eepshvqajtuvibpohsxu[cite: 13]
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${PORT:8085}
  servlet:
    context-path: /demo-ds-univalle

app:
  jwt:
    secret: ${JWT_SECRET:clave-de-desarrollo-cambiar-en-produccion-0123456789}
    expiracion-horas: 24