
spring:
  datasource:
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.co:6543/postgres?sslmode=require
    username: postgres.eepshvqajtuvibpohsxu
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    url: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.co:6543/postgres?sslmode=require
    user: postgres.eepshvqajtuvibpohsxu
    password: ${SUPABASE_DB_PASSWORD}
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: ${PORT:8085}
  servlet:
    context-path: /demo-ds-univalle

    